name: Waka Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y.%m.%d %H:%M:%S"
          SHOW_LINES_OF_CODE: "True"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          IGNORED_REPOS: "ferreroxc,ai-project-2018"
